INSERT INTO CATEGORY (ID, TYPE) VALUES (1, 'Comic-book');
INSERT INTO CATEGORY (ID, TYPE) VALUES (2, 'SiFi');
INSERT INTO CATEGORY (ID, TYPE) VALUES (3, 'Romance');

INSERT INTO BOOKS (ID, CATEGORY, TITLE, DESCRIPTION, PRICE, IMAGE, STATUS, QUANTITY) VALUES (1, 3, 'Love in the air', 'romantic chickflick', 45, '', 'pending', 54);
INSERT INTO BOOKS (ID, CATEGORY, TITLE, DESCRIPTION, PRICE, IMAGE, STATUS, QUANTITY) VALUES (2, 2, 'Clowning around', 'comedy lol', 25, '', 'pending', 2);
INSERT INTO BOOKS (ID, CATEGORY, TITLE, DESCRIPTION, PRICE, IMAGE, STATUS, QUANTITY) VALUES (3, 1, 'Spider-man', 'action pack', 20, '', 'pending', 10);
INSERT INTO BOOKS (ID, CATEGORY, TITLE, DESCRIPTION, PRICE, IMAGE, STATUS, QUANTITY) VALUES (4, 1, 'Spider-man 2', 'sequel', 10, '', 'pending', 20);

